version: '3'

services:
  php-dev:
    image: 'webdevops/php-nginx-dev:8.4'
    user: '${UID:-1000}'
    container_name: '${APP_NAME}-php'
    working_dir: /var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - './:/var/www/html'
      - '~/.ssh:/home/application/.ssh'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-php.rule=Host(`${APP_NAME}.localhost`)"
      - "traefik.http.routers.${APP_NAME}-php.entrypoints=web"
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - app

  npm-dev:
    image: node:14
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - './:/var/www/html'

  phpmyadmin:
    image: 'phpmyadmin:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-phpmyadmin.rule=Host(`${APP_NAME}-pma.localhost`)"
      - "traefik.http.routers.${APP_NAME}-phpmyadmin.entrypoints=web"
    links:
      - "mysql:db"
    depends_on:
      - mysql
    networks:
      - app

networks:
  app:
    driver: bridge
volumes:
  mysql:
    driver: local
